name: codacy-coverage-reporter

on: ["push"]

jobs:
  codacy-analysis-cli:
    name: Codacy Analysis CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master

#  codacy-coverage-reporter:
#    runs-on: ubuntu-latest
#    name: Codacy Coverage Reporter
#    steps:
#      - uses: actions/checkout@v2
#      - name: Run codacy-coverage-reporter
#        uses: codacy/codacy-coverage-reporter-action@v1
#        with:
#          api-token: ${{ secrets.CODACY_API_TOKEN }}
#          coverage-reports: cobertura.xml
